org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
enabled_platforms=fabric,neoforge

archives_base_name=wild-behavior
mod_version=1.2.3
maven_group=com.wildbehavior

architectury_api_version=21.0.7
fabric_loader_version=0.19.3
fabric_api_version=0.156.0+26.2
neoforge_version=26.2.0.43-beta

modmenu_version=20.0.1
cloth_config_version=26.2.155
